import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { GoogleOAuthProvider } from '@react-oauth/google';

const epilogue = Epilogue({ subsets: ["latin"], weight: ["300", "400", "600", "700"] });

const clientId: string = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || '';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={clientId}>
      <html lang="en">
        <body className={`${epilogue.className} font-epilogue flex flex-col min-h-screen`}>
          <Navbar />
          <main className="flex-grow w-full">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </GoogleOAuthProvider>
  );
}
